services:
  mc-fabric-server:
    image: itzg/minecraft-server:latest
    container_name: mc-fabric-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 25565:25565 # Java
      - 19132:19132/udp # Bedrock
      - 25565:25565/udp # Plasmo Voice
    environment:
      EULA: "true"
      TYPE: "FABRIC"
      VERSION: "26.1.2"
      MEMORY: "4G"
      MODRINTH_PROJECTS: |
        fabric-api
        ferrite-core
        lithium
        jade:beta
        krypton
        c2me-fabric:alpha
        spark
        chunky
        plasmo-voice
        geyser:beta
        floodgate
        fastback
    volumes:
      - ./data:/data
